// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-index-file.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import BaseActionList from './components/BaseActionList/BaseActionList.vue'
import BaseAvatar from './components/BaseAvatar/BaseAvatar.vue'
import BaseAvatarGroup from './components/BaseAvatarGroup/BaseAvatarGroup.vue'
import BaseBadge from './components/BaseBadge/BaseBadge.vue'
import BaseBlanket from './components/BaseBlanket/BaseBlanket.vue'
import BaseBreadcrumb from './components/BaseBreadcrumb/BaseBreadcrumb.vue'
import BaseButton from './components/BaseButton/BaseButton.vue'
import BaseCard from './components/BaseCard/BaseCard.vue'
import BaseCardFooter from './components/BaseCardFooter/BaseCardFooter.vue'
import BaseCardHeader from './components/BaseCardHeader/BaseCardHeader.vue'
import BaseCardSection from './components/BaseCardSection/BaseCardSection.vue'
import BaseCheckbox from './components/BaseCheckbox/BaseCheckbox.vue'
import BaseChoiceList from './components/BaseChoiceList/BaseChoiceList.vue'
import BaseColorPicker from './components/BaseColorPicker/BaseColorPicker.vue'
import BaseDatePicker from './components/BaseDatePicker/BaseDatePicker.vue'
import BaseDisplayText from './components/BaseDisplayText/BaseDisplayText.vue'
import BaseFileUpload from './components/BaseFileUpload/BaseFileUpload.vue'
import BaseFrame from './components/BaseFrame/BaseFrame.vue'
import BaseHeading from './components/BaseHeading/BaseHeading.vue'
import BaseIcon from './components/BaseIcon/BaseIcon.vue'
import BaseInlineMessage from './components/BaseInlineMessage/BaseInlineMessage.vue'
import BaseLayout from './components/BaseLayout/BaseLayout.vue'
import BaseLayoutAnnotatedSection from './components/BaseLayoutAnnotatedSection/BaseLayoutAnnotatedSection.vue'
import BaseLayoutSection from './components/BaseLayoutSection/BaseLayoutSection.vue'
import BaseModal from './components/BaseModal/BaseModal.vue'
import BaseOptionList from './components/BaseOptionList/BaseOptionList.vue'
import BasePage from './components/BasePage/BasePage.vue'
import BasePageContent from './components/BasePageContent/BasePageContent.vue'
import BasePageHeader from './components/BasePageHeader/BasePageHeader.vue'
import BasePopover from './components/BasePopover/BasePopover.vue'
import BaseProgressBar from './components/BaseProgressBar/BaseProgressBar.vue'
import BaseRadioButton from './components/BaseRadioButton/BaseRadioButton.vue'
import BaseRangeSlider from './components/BaseRangeSlider/BaseRangeSlider.vue'
import BaseSelect from './components/BaseSelect/BaseSelect.vue'
import BaseSpinner from './components/BaseSpinner/BaseSpinner.vue'
import BaseStack from './components/BaseStack/BaseStack.vue'
import BaseStackItem from './components/BaseStackItem/BaseStackItem.vue'
import BaseSubheading from './components/BaseSubheading/BaseSubheading.vue'
import BaseTag from './components/BaseTag/BaseTag.vue'
import BaseTextContainer from './components/BaseTextContainer/BaseTextContainer.vue'
import BaseTextField from './components/BaseTextField/BaseTextField.vue'
import BaseTextStyle from './components/BaseTextStyle/BaseTextStyle.vue'
import BaseToggle from './components/BaseToggle/BaseToggle.vue'
import BaseTopBar from './components/BaseTopBar/BaseTopBar.vue'

// Export components individually
export { BaseActionList, BaseAvatar, BaseAvatarGroup, BaseBadge, BaseBlanket, BaseBreadcrumb, BaseButton, BaseCard, BaseCardFooter, BaseCardHeader, BaseCardSection, BaseCheckbox, BaseChoiceList, BaseColorPicker, BaseDatePicker, BaseDisplayText, BaseFileUpload, BaseFrame, BaseHeading, BaseIcon, BaseInlineMessage, BaseLayout, BaseLayoutAnnotatedSection, BaseLayoutSection, BaseModal, BaseOptionList, BasePage, BasePageContent, BasePageHeader, BasePopover, BaseProgressBar, BaseRadioButton, BaseRangeSlider, BaseSelect, BaseSpinner, BaseStack, BaseStackItem, BaseSubheading, BaseTag, BaseTextContainer, BaseTextField, BaseTextStyle, BaseToggle, BaseTopBar }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('BaseActionList', BaseActionList)
  Vue.component('BaseAvatar', BaseAvatar)
  Vue.component('BaseAvatarGroup', BaseAvatarGroup)
  Vue.component('BaseBadge', BaseBadge)
  Vue.component('BaseBlanket', BaseBlanket)
  Vue.component('BaseBreadcrumb', BaseBreadcrumb)
  Vue.component('BaseButton', BaseButton)
  Vue.component('BaseCard', BaseCard)
  Vue.component('BaseCardFooter', BaseCardFooter)
  Vue.component('BaseCardHeader', BaseCardHeader)
  Vue.component('BaseCardSection', BaseCardSection)
  Vue.component('BaseCheckbox', BaseCheckbox)
  Vue.component('BaseChoiceList', BaseChoiceList)
  Vue.component('BaseColorPicker', BaseColorPicker)
  Vue.component('BaseDatePicker', BaseDatePicker)
  Vue.component('BaseDisplayText', BaseDisplayText)
  Vue.component('BaseFileUpload', BaseFileUpload)
  Vue.component('BaseFrame', BaseFrame)
  Vue.component('BaseHeading', BaseHeading)
  Vue.component('BaseIcon', BaseIcon)
  Vue.component('BaseInlineMessage', BaseInlineMessage)
  Vue.component('BaseLayout', BaseLayout)
  Vue.component('BaseLayoutAnnotatedSection', BaseLayoutAnnotatedSection)
  Vue.component('BaseLayoutSection', BaseLayoutSection)
  Vue.component('BaseModal', BaseModal)
  Vue.component('BaseOptionList', BaseOptionList)
  Vue.component('BasePage', BasePage)
  Vue.component('BasePageContent', BasePageContent)
  Vue.component('BasePageHeader', BasePageHeader)
  Vue.component('BasePopover', BasePopover)
  Vue.component('BaseProgressBar', BaseProgressBar)
  Vue.component('BaseRadioButton', BaseRadioButton)
  Vue.component('BaseRangeSlider', BaseRangeSlider)
  Vue.component('BaseSelect', BaseSelect)
  Vue.component('BaseSpinner', BaseSpinner)
  Vue.component('BaseStack', BaseStack)
  Vue.component('BaseStackItem', BaseStackItem)
  Vue.component('BaseSubheading', BaseSubheading)
  Vue.component('BaseTag', BaseTag)
  Vue.component('BaseTextContainer', BaseTextContainer)
  Vue.component('BaseTextField', BaseTextField)
  Vue.component('BaseTextStyle', BaseTextStyle)
  Vue.component('BaseToggle', BaseToggle)
  Vue.component('BaseTopBar', BaseTopBar)
}

// Export the library as a plugin
export default { install: install }
