// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-index-file.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import BaseAvatar from './BaseAvatar.vue'
import BaseBreadcrumb from './BaseBreadcrumb.vue'
import BaseButton from './BaseButton.vue'
import BaseCard from './BaseCard.vue'
import BaseCardFooter from './BaseCardFooter.vue'
import BaseCardHeader from './BaseCardHeader.vue'
import BaseCardSection from './BaseCardSection.vue'
import BaseDisplayText from './BaseDisplayText.vue'
import BaseFrame from './BaseFrame.vue'
import BaseHeading from './BaseHeading.vue'
import BaseIcon from './BaseIcon.vue'
import BaseInput from './BaseInput.vue'
import BaseLayout from './BaseLayout.vue'
import BaseLayoutAnnotatedSection from './BaseLayoutAnnotatedSection.vue'
import BaseLayoutSection from './BaseLayoutSection.vue'
import BasePage from './BasePage.vue'
import BasePageContent from './BasePageContent.vue'
import BasePageHeader from './BasePageHeader.vue'
import BasePopover from './BasePopover.vue'
import BaseStack from './BaseStack.vue'
import BaseStackItem from './BaseStackItem.vue'
import BaseSubheading from './BaseSubheading.vue'
import BaseTextContainer from './BaseTextContainer.vue'
import BaseTextStyle from './BaseTextStyle.vue'
import BaseTopBar from './BaseTopBar.vue'

// Export components individually
export { BaseAvatar, BaseBreadcrumb, BaseButton, BaseCard, BaseCardFooter, BaseCardHeader, BaseCardSection, BaseDisplayText, BaseFrame, BaseHeading, BaseIcon, BaseInput, BaseLayout, BaseLayoutAnnotatedSection, BaseLayoutSection, BasePage, BasePageContent, BasePageHeader, BasePopover, BaseStack, BaseStackItem, BaseSubheading, BaseTextContainer, BaseTextStyle, BaseTopBar }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('BaseAvatar', BaseAvatar)
  Vue.component('BaseBreadcrumb', BaseBreadcrumb)
  Vue.component('BaseButton', BaseButton)
  Vue.component('BaseCard', BaseCard)
  Vue.component('BaseCardFooter', BaseCardFooter)
  Vue.component('BaseCardHeader', BaseCardHeader)
  Vue.component('BaseCardSection', BaseCardSection)
  Vue.component('BaseDisplayText', BaseDisplayText)
  Vue.component('BaseFrame', BaseFrame)
  Vue.component('BaseHeading', BaseHeading)
  Vue.component('BaseIcon', BaseIcon)
  Vue.component('BaseInput', BaseInput)
  Vue.component('BaseLayout', BaseLayout)
  Vue.component('BaseLayoutAnnotatedSection', BaseLayoutAnnotatedSection)
  Vue.component('BaseLayoutSection', BaseLayoutSection)
  Vue.component('BasePage', BasePage)
  Vue.component('BasePageContent', BasePageContent)
  Vue.component('BasePageHeader', BasePageHeader)
  Vue.component('BasePopover', BasePopover)
  Vue.component('BaseStack', BaseStack)
  Vue.component('BaseStackItem', BaseStackItem)
  Vue.component('BaseSubheading', BaseSubheading)
  Vue.component('BaseTextContainer', BaseTextContainer)
  Vue.component('BaseTextStyle', BaseTextStyle)
  Vue.component('BaseTopBar', BaseTopBar)
}

// Export the library as a plugin
export default { install: install }
