// THIS FILE IS AUTOMATICALLY GENERATED IN:
//
//   build-utils/update-index-file.js
//
// YOU SHOULD NEVER UPDATE THIS FILE DIRECTLY

import BaseButton from './BaseButton.vue'

// Export components individually
export { BaseButton }

// What should happen if the user installs the library as a plugin
function install(Vue) {
  Vue.component('BaseButton', BaseButton)
}

// Export the library as a plugin
export default { install: install }
